# Generated by Django 4.2.4 on 2023-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, default=0)),
                ('cover_image', models.URLField(blank=True)),
            ],
        ),
    ]
